<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

  <PropertyGroup>
    <!-- xUnit convention uses underscore-separated test method names. -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
