namespace XApiSharp.CodeGen;

/// <summary>
/// GEN-04: every generated file carries a repo-level autogeneration marker (in addition to
/// NSwag's own per-class [GeneratedCode] attribute) so it's unambiguous at a glance that manual
/// edits belong in a partial class / override, not in this file.
/// </summary>
internal static class GeneratedFileStamper
{
    public static void Stamp(string filePath, string snapshotPath)
    {
        var sha256 = FileHash.Sha256(snapshotPath);
        var banner = $"""
            // <auto-generated>
            //   This file was produced by tools/XApiSharp.CodeGen from {snapshotPath}
            //   (snapshot sha256: {sha256}). Do not edit by hand - changes belong in a partial
            //   class, a template, or spec/overrides/. See docs/adr/0002-code-generation.md.
            // </auto-generated>

            """;

        var original = File.ReadAllText(filePath);
        File.WriteAllText(filePath, banner + original);
    }
}
